apiVersion: apps/v1
kind: Deployment
metadata:
  name: architacturalapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: architacturalapi
  template:
    metadata:
      labels:
        app: architacturalapi
    spec:
      containers:
        - name: architacturalapi
          image: 735521274598293/architacturalapi:latest
          ports:
            - containerPort: 8080
          env:
            - name: ConsulVersion
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: ConsulVersion
            - name: ApiVersion
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: ApiVersion
            - name: ApiUserName
              valueFrom:
                secretKeyRef:
                  name: architectural-secret
                  key: username
            - name: ApiPassword
              valueFrom:
                secretKeyRef:
                  name: architectural-secret
                  key: password
