apiVersion: apps/v1
kind: Deployment
metadata:
  name: architacturalapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: architacturalapi
  template:
    metadata:
      labels:
        app: architacturalapi
    spec:
      containers:
        - name: architacturalapi
          image: 735521274598293/architacturalapi:latest
          securityContext:
            runAsUser: 0 # This specifies running as the root user
            runAsGroup: 0 # This specifies running as the root group
          ports:
            - containerPort: 8080
          env:
            - name: ConsulVersion
              valueFrom:
                configMapKeyRef:
                  name: archdesignapi-config
                  key: ConsulVersion
            - name: ApiVersion
              valueFrom:
                configMapKeyRef:
                  name: archdesignapi-config
                  key: ApiVersion
            - name: ApiUserName
              valueFrom:
                secretKeyRef:
                  name: archdesignapi-secret
                  key: username
            - name: ApiPassword
              valueFrom:
                secretKeyRef:
                  name: archdesignapi-secret
                  key: password
          volumeMounts:
            - name: filedata
              mountPath: /app/Logs
      volumes:
        - name: filedata
          persistentVolumeClaim:
            claimName: file-volume
