apiVersion: v1
kind: Service
metadata:
  name: architacturalapi-service
spec:
  type: NodePort
  selector:
    app: architacturalapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30008
